# Global parameter defaults
path: http
url: http://blog.nws.co.uk
user: admin
color: false

# Subcommand defaults (e.g. `wp config create`)
config create:
    dbhost: localhost
    dbname: wordpress-nws-2019
    dbuser: root
    dbpass: root
    extra-php: |
        define( 'WP_DEBUG', true );
        define( 'WP_MEMORY_LIMIT', '256M' );

core install:
    title: Blog | Net World Sports
    admin_user: admin
    admin_password: password
    admin_email: admin@example.com

core multisite-install:
        subdomains: true
        title: Blog | Net World Sports
        admin_user: admin
        admin_password: password
        admin_email: mohamed@networldsports.com