# Global parameter defaults
path: http
url: https://blog.networldsports.co.uk
user: admin
color: false

# Subcommand defaults (e.g. `wp config create`)
config create:
    dbhost: 'localhost'
    dbname: 'blog-staging'
    dbuser: 'nws_blog'
    dbpass: 'j9C?7#EH'
    extra-php: |
        define( 'WP_DEBUG', true );
        define( 'WP_MEMORY_LIMIT', '256M' );

core install:
    title: Networld Blog
    admin_user: admin
    admin_password: admin12345
    admin_email: aaron@networldsports.com

core multisite-install:
    subdomains: true
    title: Sample Title
    admin_user: admin
    admin_password: password
    admin_email: ashley@networldsports.com
